# soc_rating:
#     resource: "@SocBundle/Controller/RatingController.php"
#     type:     annotation

soc_price:
    resource: "@SocBundle/Controller/PriceController.php"
    type:     annotation

soc_category:
    resource: "@SocBundle/Controller/CategoryController.php"
    type:     annotation

soc:
    resource: "@SocBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
