soc_product:
    resource: "@SocBundle/Resources/config/routing/product.yml"
    prefix:   /product

soc_homepage:
    path:     /
    defaults: { _controller: SocBundle:Default:index }

soc_users:
    path:     /users
    defaults: { _controller: SocBundle:User:users }

user_show:
    path:     /user/{id}/show
    defaults: { _controller: "SocBundle:User:show" }
    methods:  [GET, POST]

user_new:
    path:     /user/new
    defaults: { _controller: "SocBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /user/{id}/edit
    defaults: { _controller: "SocBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /user/{id}/delete
    defaults: { _controller: "SocBundle:User:delete" }
    methods:  DELETE

user_admin:
    path:     /user/{id}/admin
    defaults: { _controller: "SocBundle:User:admin" }
    methods:  [GET, POST]

json_categ:
    path:     /product/json/categories
    defaults: { _controller: "SocBundle:Json:categories"}
    methods:  [POST]

rating_new:
    path:     /rating/{id}/{type}/new
    defaults: { _controller: "SocBundle:Rating:new" }
    methods:  [GET, POST]

price_new:
    path:     /price/{id}/new
    defaults: { _controller: "SocBundle:Price:new" }
    methods:  [GET, POST]

bid_new:
    path:     /bid/{id}/new
    defaults: { _controller: "SocBundle:Bid:new" }
    methods:  [GET, POST]

product_buy:
    path:     /bid/{id}/new
    defaults: { _controller: "SocBundle:Bid:new" }
    methods:  [GET, POST]
